### ISSUE TITLE
rough set of ideas for rewrite

### ISSUE THREAD

**Issue by PF94** [carrevue/OpenSB#230]
# Sites

* have the codebase be more dynamic in terms of enabling and disabling functionality between "site modes"
* lock frontends between "site modes"
* disable content filtering functionality in squarebracket mode

| site  | frontends | example |
|---|---|---|
| squareBracket | Biscuit (along with Bootstrap and Finalium) | ![Screen Shot 2024-07-16 at 11 59 04](https://github.com/user-attachments/assets/700684f2-8922-48d6-9451-28a306f425d8) |
| Second Official OpenSB Site | biscuit-like frontend? | ![Frame 2(2)](https://github.com/user-attachments/assets/536e3452-a75e-4ba0-a608-11273fb641d3) |

# General SB features
* "playlists"
* reimplement favorites (they were briefly implemented on pokTwo and later brought over to OpenSB1 in 2022-2023 but werent fully finished)
* improve upon the tagging system
* have one table for comments in the database
* possibly merge posts/journals with comments
* support oauth (and possibly bittoco accounts if sb gets integrated into bittoco)
* don't hardcore privacy policy, terms of service, rules and guidelines pages

# sbChat
* add friends, contact list
* add private messaging
* add way of making seperate chatrooms (general for gamerappium 8 discord and squarebracket, and a seperate channel for games like blockland)
* msnp

# Database
* rename stuff to be more consistent

| Old                   | Planned             |
|-----------------------|---------------------|
| activitypub_sites     | [removed]           |
| activitypub_user_urls | [removed]           |
| bans                  | user_ban            |
| blacklisted_referer   | [removed]           |
| channel_comments      | comment/post(?)     |
| comments              | comment/post(?)     |
| deleted_videos        | upload_deleted      |
| favorites             | user_favorite       |
| invite_keys           | site_invite_key     |
| ipbans                | site_ip_ban         |
| journals              | journal/post(?)     |
| journal_comments      | comment/post(?)     |
| notifications         | notification        |
| passwordresets        | user_password_reset |
| rating                | upload_rating       |
| site_settings         | [removed]           |
| subscriptions         | user_follow         |
| suggestions           | [removed]           |
| tax_index             | tag_index           |
| tag_meta              | tag_info            |
| takedowns             | upload_takedown     |
| users                 | user                |
| user_old_names        | user_old_name       |
| user_staff_notes      | user_staff_note     |
| videos                | upload              |
| views                 | upload_view         |

* remove leftovers from principia-web in tables (group_id in user for example)

**Comment by sdpj** [comment]
> support oauth (and possibly bittoco accounts if sb gets integrated into bittoco)

some suggestions for auth providers:
- indieauth
- discord
- github
- mastodon
- [scratchauth](https://auth.itinerary.eu.org) (for development, probably not production)
- qfx (most likely not as bittoco integration is planned, and 3rd party auth is not supported (yet))
