### ISSUE TITLE
display names can be completely blank

### ISSUE THREAD

**Issue by PF94** [carrevue/OpenSB#234]
![image](https://github.com/user-attachments/assets/6fc4c073-bd95-49f1-ba6d-e8e35152c3ac)

![image](https://github.com/user-attachments/assets/a2027736-b575-4c66-9b12-9a2e381e3950)
(okay this one has a blank user due to a now-patched bug but still)

**Comment by sdpj** [comment]
yeah you should just make [display name] automatically set to username

**Comment by PF94** [comment]
fixed in https://github.com/bluffingo/OpenSB/commit/1496a35e9ed985f406e296cab88960aa48a37e2e
