### ISSUE TITLE
squarebracket is WOKE!!!!!!

### ISSUE THREAD

**Issue by yuptune** [carrevue/OpenSB#238]
stop spreading the woke mind virus with your site...... its bad

**Comment by yuptune** [comment]
![thumbdevil.png](https://github.com/user-attachments/assets/d96613c3-d2d1-4574-b828-e31816e73cc7)

**Comment by sdpj** [comment]
luna shut the fuck up

**Comment by PF94** [comment]
please do not shitpost in the opensb repository. github issues should only be used for serious matters.
