### ISSUE TITLE
repo link is still squarebracket.pw while main domain has moved to squarebracket.me

### ISSUE THREAD

**Issue by sdpj** [carrevue/OpenSB#241]
![image](https://github.com/user-attachments/assets/b616c54d-774c-4c67-b1a3-5530cc8c1245)
![image](https://github.com/user-attachments/assets/e4b5aee1-ccb1-41c6-948d-fabe15bd1642)

since squarebracket.pw could be taken over at any point in time i think it should be updated

**Comment by PF94** [comment]
oh shit forgot to close this
