### ISSUE TITLE
github link on /version does not work correctly

### ISSUE THREAD

**Issue by sdpj** [carrevue/OpenSB#253]
![image](https://github.com/user-attachments/assets/d6f08303-53f9-4732-86fb-07661555862e)
it tries to link to here

**Comment by sdpj** [comment]
@PF94 Have you seen this 👀

**Comment by yuptune** [comment]
i'll make a commit

**Comment by yuptune** [comment]
dude what the fuck is this code

**Comment by rollerozxa** [comment]
https://github.com/bluffingo/OpenSB/blob/main/private/skins/biscuit/templates/version.twig#L41

seems to simply be a stray leading slash in the link

**Comment by PF94** [comment]
fixed

**Comment by PF94** [comment]
the mistake first showed up on https://github.com/bluffingo/OpenSB/commit/96781e5e90cfd65c7248f172c9110a3b2e32f758#diff-32352a7d5a590aa4050eb03da88cda7ecd912013ded51771be1fe588bb24adadR36
